{% set name = "pbr" %}
{% set version = "5.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "42df03e7797b796625b1029c0400279c7c34fd7df24a7d7818a1abb5b38710dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pbr = pbr.cmd.main:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - pip

test:
  imports:
    - pbr
    - pbr.cmd
    - pbr.hooks

  commands:
    - pbr --help

about:
  home: https://launchpad.net/pbr
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Python Build Reasonableness
  doc_url: https://docs.openstack.org/developer/pbr/
  dev_url: https://git.openstack.org/cgit/openstack-dev/pbr

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - tschoonj
